name: generator_test
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build_test: ^2.1.5
  dart_style: ^2.2.1
  meta: ^1.7.0
  source_gen: ^1.2.1

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

scripts: derry.yaml

import_sorter:
  comments: false