name: generator_test
description: A library to help test generators and build runner packages using dart files instead of Strings
version: 0.3.0
repository: https://github.com/mrgnhnt96/generator_test
homepage: https://github.com/mrgnhnt96/generator_test

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build: ^2.2.1
  build_test: ^2.1.5
  dart_style: ^2.2.1
  logging: ^1.0.2
  meta: ^1.7.0
  path: ^1.9.0
  source_gen: ^1.2.1

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

scripts: derry.yaml

import_sorter:
  comments: false