name: generator_test
description: A library to help test generators and build runner packages using dart files instead of Strings
version: 0.3.1
repository: https://github.com/mrgnhnt96/generator_test
homepage: https://github.com/mrgnhnt96/generator_test

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  build: ^2.4.2
  build_test: ^2.2.3
  dart_style: ^3.0.1
  logging: ^1.3.0
  meta: ^1.16.00
  path: ">=1.9.0 <=1.19.1"
  source_gen: ^2.0.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0

scripts: derry.yaml

import_sorter:
  comments: false